project:
  type: website
  output-dir: ../docs

website:
  title: "Hisatake Ishida"
  navbar:
    left:
      - href: hisatakeishida.github.io.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    toc: true

editor: visual